config/routes.rb
NattfoddsLair::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'posts#index'

  get "drafts" => 'posts#draft_list'
  get '/:url' => 'categories#show', as: :category 

  resources :posts do 
    resources :comments
  end

  resources :categories

  

end

app/models/category.rb
class Category < ActiveRecord::Base
    validates_uniqueness_of :url

    def to_param
        url
    end

    def self.find_by_param(input)
        find_by_url(input)
    end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :category

  self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_404
    render :status => 404
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show 
        @posts = Post
        cat_id = Category.find_by_param(params[:url])
        unless cat_id.nil?
            @posts = Post.paginate(page: params[:page]).where(status: 1).where(category_id: cat_id.id).order("created_at DESC")
            render "posts/index"
        else
            render :status => 404
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :find_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_filter :user_is_admin, only: [:new, :edit, :update, :destroy]
  before_filter :get_categories

  def index 
    @posts = Post
    @posts = Post.paginate(page: params[:page]).where(status: 1).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create 
    @post = Post.new(post_params)
    @post.user = current_user
    if params[:publish]
      @post.status = 1
      @post.was_published = 1
    else 
      @post.status = 0
    end
    @post.save
    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def show
    if @post.status == 1
      unless user_signed_in? and @post.user_id == current_user.id 
        @post.increment!(:views)
      end
    else
      unless user_signed_in? and @post.user_id == current_user.id
        render_404
      end
    end
  end

  # /posts/1/edit GET
  def edit 
  end

  # /post/1 PUT
  def update
    @post.update_attributes(post_params)
    if params[:publish]
      if @post.was_published == 0     
        @post.created_at = DateTime.now 
        @post.was_published = 1
      end
      @post.status = 1
    else
      @post.status = 0
    end
    @post.save

    if @post.errors.empty?
      redirect_to post_path(@post)
    else
      if params[:publish]
        render "edit"
      else 
        redirect_to "index"
      end
    end  
  end

  def destroy
    @post.destroy
    redirect_to action: "index"
  end

  def draft_list
    @posts = Post
    @posts = Post.paginate(page: params[:page]).where(status: 0, user_id: current_user.id).order("created_at DESC")
    render "index"
  end

private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end

    def find_post
      @post = Post.find_by_id(params[:id])
      if @post.nil? 
        render_404
      end
    end 

    def user_is_admin 
      redirect_to action: "index" unless current_user.role == 1
    end

    def get_categories 
      @cat = Category.find(:all)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def before_cut(text)
    cutted_text = text.split('[cut]', 2)
    return cutted_text[0]
  end

  def delete_cut(text)
    text.gsub!(/\[cut\]/, "")
    return text
  end

  def has_cut?(text)
    text.index(/\[cut\]/)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru-RU">
<head>
  <title>Nattfodds Lair</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
    CKEDITOR.config.contentsCss = "
    <% asset_path('main.css') %>
    ";
    
    $('.selectpicker').selectpicker();
  </script>
</head>
  <% if user_signed_in? %>
    <body class="body_orange_w_navbar">
    <%= render "shared/navbar" %>
  <% else %>
    <body class="body_orange_no_navbar">
  <% end %>

  <div class="container-fixed">
    <div class="page-header">
    <%= link_to root_url do %>
      <p class="blog-name">Nattfodd's Lair</p>
    <% end %>
    </div>

    <div class="header-stripe">
      <ul class="menu-stripe">
        <% @cat = Category.find(:all) %>
        <% @cat.each do |c| %>
          <li><%= link_to c.name, c %></li>
        <% end %> 
      </ul>
    </div>   

    <p class="notice hidden"><%= notice %></p>
    <p class="alert hidden"><%= alert %></p>

<%= yield %>

  </div>
  <div class="block-footer">
    <div class="block-footer-dashed">
      <p class="pull-left">
        <% unless user_signed_in? %>
        <%= link_to 'Войти на сайт', new_user_session_path %>
        <% end %>
      </p>
      <p>Copyright by <a href="mailto:mail@nattfodd.com">Oleksii Kuznietsov</a> 2010-2013</p>
       <%= image_tag('boy.png', alt: 'img-boy') %>
    </div> 
  </div>  
  <div class="pop-up">
    <div class="pop-up-register">
      <div class="pop-up-dashed">
        <h1>Регистрация:</h1>
        <p>Ник:</p>
        <div class="input-group">
          <span class="input-group-addon">@</span>
          <input type="text" class="form-control" placeholder="login">        
        </div>
        <p>Почта:</p>
        <div class="input-group">
          <span class="input-group-addon">@</span>
          <input type="text" class="form-control" placeholder="e-mail">       
        </div>    
        <p>Пароль:</p>
        <div class="input-group">
          <span class="input-group-addon">@</span>
          <input type="text" class="form-control" placeholder="password">       
        </div>              
        <p>Повторите пароль:</p>
        <div class="input-group">
          <span class="input-group-addon">@</span>
          <input type="text" class="form-control" placeholder="password one more time">       
        </div>  
        <div class="btn-container">
          <button type="button" class="btn btn-primary btn-lg pull-left">Отменить</button>
          <button type="button" class="btn btn-success btn-lg pull-right">Зарегистрироваться</button>
        </div>                
      </div>
    </div>      
  </div>  
</body>
</html>

app/views/posts/edit.html.erb
<div class="dashed-article-page">
<div class="content-wrapper">
<%= render partial: "shared/form", locals: {post: @post} %>
<div class="block-footer-push"></div>
</div>
</div>

app/views/posts/index.html.erb
    <div class="dashed-article-page">
      
      <% @posts.each do |p| %>
        <%= render 'shared/single_article', post: p %>
      <% end %>
      <%= will_paginate @posts %>
      <div class="block-footer-push"></div>
    </div>

app/views/posts/new.html.erb
<div class="dashed-article-page">
<div class="content-wrapper">
<%= render partial: "shared/form", locals: {post: @post} %>
<div class="block-footer-push"></div>
</div>
</div>

app/views/posts/show.html.erb
      <!-- Article -->
    <div class="dashed-article-page">
    <div class="content-wrapper">
    <% if @post.nil? %>
      <h1>Пост не найден</h1>
    <% else %>
      <% if @post.status == 1 or (user_signed_in? and @post.user_id == current_user.id) %>
        <div class="post-date-blue">
          <p class="post-date-text-blue">
            <i class="icon-calendar-empty"></i> 
            <%= l @post.created_at,  format: :short %>
          </p>
        </div>
        <div class="post-title">
          <h1>
            <%= @post.title %>
          </h1>
          <% if user_signed_in? %>
            <p>
              <%= link_to "Редактировать", edit_post_path(@post) %>
            </p><p>
              <%= link_to 'Удалить', post_path(@post), data: { confirm: 'Уверен?' }, :method => :delete %>
            </p>
          <% end %>
        </div>
        <div class="article">
          <%= raw delete_cut(@post.body) %>
        </div>
        <div class="under-article">
          <p>Комментарии (<%= @post.comments.count %>)</p>
        </div>
        <%= image_tag('separator.png', class: 'separator') %>

        <!-- Comments -->
        <div class="block-comments"> 
          <%= render "shared/comments" %>
          <%= render 'shared/comment_form' %> 
        </div>   
      <% else %>
        <h1>У вас нет прав для просмотра этого поста</h1>
      <% end %>  
    <% end %>  
      <!-- Footer -->
      <div class="block-footer-push"></div>
    </div>
    </div>

app/views/shared/_comment_form.html.erb
<% if user_signed_in? %>
  <%= form_for ([@post, @post.comments.build]) do |f| %>
    <%= f.text_area :body, class: "form-control" %>
    <%= f.submit "Отправить", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <div>Чтобы оставлять комментарии, нужно 
    <%= link_to "зарегистрироваться", new_user_registration_path %>
    или 
    <%= link_to "войти", new_user_session_path %>
    под своим аккаунтом.
  </div>
<% end %>  

app/views/shared/_comments.html.erb
<a href="#comments"></a>
<div class="media">
<% @post.comments.each do |comment| %>
    <div class="media-body">
      <div class="media-heading">
        <strong><%= comment.user.name %></strong> оставил комментарий <%= l comment.created_at, format: :long %>
      </div>
      <div class="comment-wrapper"><%= simple_format(comment.body) %></div>
    </div>
<% end %>
</div>

app/views/shared/_form.html.erb
<%= form_for post do |form| -%>
  <%= form.text_field :title, class: "form-control" %>
  <%= form.select :category_id, Category.find(:all).collect { |a| [a.name, a.id] }, { include_blank: true }, { class: "selectpicker", id: "selectpicker", selected: @post.category_id,  } %>
  <%= form.cktext_area :body, :id => "ckeditor", toolbar: "Easy" %>
  <div class="bottom-btn-toolbar">
    <% if @post.status == 0 or params[:action] == 'new' %>
      <%= form.submit "Опубликовать пост", class: "btn btn-success btn-lg", name: "publish" %>
      <%= form.submit "Сохранить в черновиках", class: "btn btn-warning btn-lg", name: "draft" %>
    <% else %> 
      <%= form.submit "Сохранить изменения", class: "btn btn-success btn-lg", name: "publish" %>
      <%= form.submit "Убрать в черновики", class: "btn btn-warning btn-lg", name: "draft" %>
    <% end %>
  </div>  
<% end -%>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="pull-left">
        <div class="menu-item"><i class="icon-edit"></i> <%= link_to "Написать пост", new_post_path %></div>  
        <div class="menu-item"><i class="icon-book"></i> <%= link_to "Черновики", controller: :posts, action: :draft_list %></div>
        <div class="menu-item"><i class="icon-bar-chart"></i> Статистика</div>
      </div>  
      <div class="pull-right">
        <i class="icon-signout"></i> <%= link_to "Выйти", destroy_user_session_path, method: :delete %>
      </div>      
    </div>
  </div>

app/views/shared/_no_rights.html.erb
<div class="dashed-article-page">
<h1>У вас нет доступа к этой странице</h1>
</div>

app/views/shared/_single_article.html.erb
<!-- Article -->
<div class="article-container">
<div class="post-date-blue">
  <p class="post-date-text-blue">
    <i class="icon-calendar-empty"></i> 
    <%= l post.created_at, format: :short %>
  </p>
</div>
<div class="post-title">
<h1>
  <%= link_to post.title, post %>
</h1>
<div class="tag-wrapper">
  <% if post.status == 0 %>
    <div class="badge tag">черновик</div>
  <% end %>
</div>  
</div>
<div class="article">
  <%= raw before_cut(post.body) %>
</div>
<% if has_cut?(post.body) %>
  <%= link_to "Читать далее", post, class: "btn btn-lrg btn-primary read-next" %></button>
<% end %>
<%= image_tag('separator.png', class: 'separator') %>
<p class="article-statistic pull-left"><i class="icon-eye-open"></i> просмотров: <%= post.views %></p>
<p class="article-statistic pull-right"><i class="icon-comment"></i> комментариев:  <%= post.comments.count %> </p>
</div>

app/views/shared/_toolbar.html.erb
<div id="wysihtml5-toolbar" style="display: none;">
    <a data-wysihtml5-command="bold" title="CTRL+B">bold</a> |
    <a data-wysihtml5-command="italic" title="CTRL+I">italic</a> |
    <a data-wysihtml5-command="createLink">insert link</a> |
    <a data-wysihtml5-command="insertImage">insert image</a> |
    <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">h1</a> |
    <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2">h2</a> |
    <a data-wysihtml5-command="insertUnorderedList">insertUnorderedList</a> |
    <a data-wysihtml5-command="insertOrderedList">insertOrderedList</a> |
    <div data-wysihtml5-dialog="insertEmbedVideo" style="display: none;">
    <a data-wysihtml5-action="change_view">switch to html view</a>
    
    <div data-wysihtml5-dialog="createLink" style="display: none;">
      <label>
        Link:
        <input data-wysihtml5-dialog-field="href" value="http://">
      </label>
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
    
    <div data-wysihtml5-dialog="insertImage" style="display: none;">
      <label>
        Image:
        <input data-wysihtml5-dialog-field="src" value="http://">
      </label>
      <label>
        Align:
        <select data-wysihtml5-dialog-field="className">
          <option value="">default</option>
          <option value="wysiwyg-float-left">left</option>
          <option value="wysiwyg-float-right">right</option>
        </select>
      </label>
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
</div>

app/views/shared/_wyshtml.html.erb
<!-- ACTION: EDIT -->
<%= form_for @post do |f| %>
  
  <%= f.text_field :title, class: "form-control" %>
  <%= render 'shared/toolbar' %>
  <%= f.text_area :body, id: 'wysihtml5-textarea' %>
  <div class="bottom-btn-toolbar">
    <% if @post.status == 0 %>
      <%= f.submit "Опубликовать пост", class: "btn btn-success btn-lg", name: "publish" %>
      <%= f.submit "Сохранить в черновиках", class: "btn btn-warning btn-lg", name: "draft" %>
    <% else %> 
      <%= f.submit "Сохранить изменения", class: "btn btn-success btn-lg", name: "publish" %>
      <%= f.submit "Убрать в черновики", class: "btn btn-warning btn-lg", name: "draft" %>
    <% end %>
  </div>
<% end %>

<script>
  var editor = new wysihtml5.Editor("wysihtml5-textarea", { // id of textarea element
    toolbar:      "wysihtml5-toolbar", // id of toolbar element
    parserRules:  wysihtml5ParserRules // defined in parser rules set 
   // html: true, //Button which allows you to edit the generated HTML. Default false
  }); 
</script>  
<div class="block-footer-push"></div>

<!-- ACTION: NEW -->

<%= form_for @post do |f| %>
  
  <%= f.text_field :title, class: "form-control", placeholder: "Заголовок поста" %>
  <%= render 'shared/toolbar' %>
  <%= f.text_area :body, id: 'wysihtml5-textarea', placeholder: 'Ваш шедевр туточки' %>
  <div class="bottom-btn-toolbar">
    <a class="btn btn-primary btn-lg">Предпросмотр</a>
    <%= f.submit "Опубликовать", class: "btn btn-success btn-lg", name: "publish" %>
    <%= f.submit "В черновики", class: "btn btn-warning btn-lg", name: "draft" %><!--
    <a class="btn btn-warning btn-lg">В черновики</a> -->
  </div>
<% end %>

<script>
  var editor = new wysihtml5.Editor("wysihtml5-textarea", { // id of textarea element
    toolbar:      "wysihtml5-toolbar", // id of toolbar element
    parserRules:  wysihtml5ParserRules // defined in parser rules set 
  });
</script> 